apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zkfsm-csi.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zkfsm-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "zkfsm-csi.labels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "zkfsm-csi.fullname" . }}-controller
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: csi-provisioner
          image: {{ .Values.provisioner.image }}
          args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --strict-topology
            - --immediate-topology=false
            - --leader-election
            - --leader-election-namespace={{ .Release.Namespace }}
            - --default-fstype={{ .Values.storageClass.fsType }}
            - --extra-create-metadata
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: zkfsm-csi
          image: {{ include "zkfsm-csi.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - controller
            - --endpoint=unix:///csi/csi.sock
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
