apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zkfsm-operator.fullname" . }}
  labels: {{- include "zkfsm-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zkfsm-operator.fullname" . }}
  labels: {{- include "zkfsm-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [zkfsm.io]
    resources: [clusters]
    verbs: [get, list, watch]
  - apiGroups: [zkfsm.io]
    resources: [clusters/status]
    verbs: [get, patch, update]
  - apiGroups: [apps]
    resources: [statefulsets, deployments]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [services, secrets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [get, list, watch, delete]
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [cert-manager.io]
    resources: [certificates]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zkfsm-operator.fullname" . }}
  labels: {{- include "zkfsm-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zkfsm-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zkfsm-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
