#!/usr/bin/env python3
"""Independent reference Reed-Solomon encoder (bitwise GF(2^8), poly 0x11D,
Cauchy parity rows 1/((k+i) xor j)). Writes src/protection/erasure_ref_vectors.zig."""
import os
import sys


def gf_mul(a, b):
    r = 0
    while b:
        if b & 1:
            r ^= a
        a <<= 1
        if a & 0x100:
            a ^= 0x11D
        b >>= 1
    return r


def gf_inv(a):
    # a^254 by square-and-multiply.
    r, e = 1, 254
    while e:
        if e & 1:
            r = gf_mul(r, a)
        a = gf_mul(a, a)
        e >>= 1
    return r


def encode(k, m, data):
    parity = []
    for i in range(m):
        row = [gf_inv((k + i) ^ j) for j in range(k)]
        out = bytearray(len(data[0]))
        for j in range(k):
            for p, x in enumerate(data[j]):
                out[p] ^= gf_mul(row[j], x)
        parity.append(bytes(out))
    return parity


def lcg(seed):
    s = seed
    while True:
        s = (s * 6364136223846793005 + 1442695040888963407) & (2**64 - 1)
        yield s >> 56


def zig_bytes(b):
    return '"' + "".join("\\x%02x" % x for x in b) + '"'


def main():
    profiles = [("EC:4+2", 4, 2), ("EC:8+4", 8, 4), ("EC:12+4", 12, 4)]
    lens = [1, 17, 64]
    lines = ["//! Generated by tests/erasure_ref.py; do not edit.", "",
             "pub const Case = struct { profile: []const u8, shard_len: usize, data: []const u8, parity: []const u8 };",
             "", "pub const cases = [_]Case{"]
    seed = 1
    for name, k, m in profiles:
        for n in lens:
            g = lcg(seed)
            seed += 1
            data = [bytes(next(g) for _ in range(n)) for _ in range(k)]
            parity = encode(k, m, data)
            lines.append("    .{ .profile = \"%s\", .shard_len = %d, .data = %s, .parity = %s },"
                         % (name, n, zig_bytes(b"".join(data)), zig_bytes(b"".join(parity))))
    lines.append("};")
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "protection",
                       "erasure_ref_vectors.zig")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(out), file=sys.stderr)


if __name__ == "__main__":
    main()
