{{- if not .Values.auth.existingSecret }}
{{- $name := include "zkfsm.fullname" . }}
{{- $old := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "zkfsm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $old }}
  accessKey: {{ index $old.data "accessKey" }}
  secretKey: {{ index $old.data "secretKey" }}
  {{- if .Values.cluster.useClusterSecret }}
  clusterSecret: {{ index $old.data "clusterSecret" | default (randAlphaNum 40 | b64enc) }}
  {{- end }}
  {{- else }}
  accessKey: {{ default (randAlphaNum 20) .Values.auth.rootUser | b64enc | quote }}
  secretKey: {{ default (randAlphaNum 40) .Values.auth.rootPassword | b64enc | quote }}
  {{- if .Values.cluster.useClusterSecret }}
  clusterSecret: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
