{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zkfsm.fullname" . }}
  labels:
    {{- include "zkfsm.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "zkfsm.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: s3
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
